name: Builders-Revival-Core
main: Core
version: 0.1
api-version: 1.13
author: Fictitious_Rotor

commands:
  test-economy:
    description: Test the economy innit

  test-permission:
    description: Test the permissions innit

  /wand:
    description: Cheeky wand interception

  say:
    description: Cheeky say interception
